modLoader="javafml"

loaderVersion="${loader_version_range}"


license="${mod_license}"

[[mods]]


modId="${mod_id}"

version="${mod_version}"

displayName="${mod_name}"

description='''
Farmer's Delight Addon that's adding
low-internet cuisine delights to your game.
'''

[[dependencies.${mod_id}]] #optional
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
modId="farmersdelight"
type="required"
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId = "crafttweaker"
type = "optional"
versionRange = "[14.0.6,)"
ordering = "NONE"
side = "BOTH"